import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://merocircle.app";
  const currentDate = new Date();

  // Core pages with highest SEO priority for Mero Circle
  const corePages = [
    {
      url: baseUrl,
      lastModified: currentDate,
      changeFrequency: "daily" as const,
      priority: 1.0,
    },
    {
      url: `${baseUrl}/explore`,
      lastModified: currentDate,
      changeFrequency: "daily" as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
  ];

  // Authentication and onboarding pages
  const authPages = [
    {
      url: `${baseUrl}/auth`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/login`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/signup`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${baseUrl}/signup/creator`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
  ];

  // Creator-focused pages (lower priority as they're tools, not discovery)
  const creatorPages = [
    {
      url: `${baseUrl}/creator-studio`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.6, // Reduced from 0.8 - it's a dashboard, not public content
    },
    {
      url: `${baseUrl}/create-post`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.5, // Reduced from 0.7 - internal tool, not for SEO
    },
  ];

  // Utility and support pages (lower priority)
  const utilityPages = [
    {
      url: `${baseUrl}/unsubscribe`,
      lastModified: currentDate,
      changeFrequency: "yearly" as const,
      priority: 0.3,
    },
    {
      url: `${baseUrl}/payment/success`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.4,
    },
    {
      url: `${baseUrl}/payment/failure`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.4,
    },
    {
      url: `${baseUrl}/payment/dodo/success`,
      lastModified: currentDate,
      changeFrequency: "monthly" as const,
      priority: 0.4,
    },
  ];

  // Sample dynamic routes (in production, these would be generated by sitemap-creators.ts)
  const sampleDynamicRoutes = [
    {
      url: `${baseUrl}/creator/sample-creator`,
      lastModified: currentDate,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
  ];

  return [
    ...corePages,
    ...authPages,
    ...creatorPages,
    ...utilityPages,
    ...sampleDynamicRoutes,
  ];
}
